#!/bin/bash
################################################################
### Shutting down sparksd.service or killing sparksd process ###
################################################################
### VARS

coin_name="sparks"
coin_daemon="sparksd"
coin_cli="sparks-cli"

################################################################

. /usr/share/debconf/confmodule
#set -e

### get username from $coin_daemon.service file ###
if [ -f "/etc/systemd/system/$coin_daemon.service" ]
then
    username=$(cat "/etc/systemd/system/$coin_daemon.service"  | grep User | cut -d "=" -f 2)
else
    db_get coinpkg/sysuser
    username=$RET
fi

### STOPPING the COINS DAEMON ###
if pgrep -x "$coin_daemon" > /dev/null
then
  if [ "$(systemctl is-active $coin_daemon)" = "active" ]
  then
    systemctl stop $coin_daemon
  fi
fi

### STOPING other coin processes if they are running ###
if [ "$(pgrep $coin_daemon)" ]
then
    for users in $(pgrep "$coin_daemon" | xargs ps -o user= -p)
    do
        sudo -i -u $users /bin/bash -l -c "$coin_cli stop" || true
        crontab -l -u $users | sed "/$coin_name crontab start/,/$coin_name crontab end/d" | crontab -u $users - || true
    done
fi

### removing cronjob of user ###
crontab -l -u $username | sed "/$coin_name crontab start/,/$coin_name crontab end/d" | crontab -u $username - || true
