#!/bin/bash

# Exit on error
set -e

# Source debconf library.
. /usr/share/debconf/confmodule

# Ask questions
db_input high coinpkg/systemd || true
db_input high coinpkg/rootuser || true
db_go || true

db_get coinpkg/rootuser

if [ "$RET" = "true" ]
then
    user_ok=''
    while [ ! "$user_ok" ]
    do
        db_input high coinpkg/sysuser || true
        db_go || true

        db_get coinpkg/sysuser
        user_exists=$(getent passwd $RET | cut -d ":" -f 1)

        if [ "$user_exists" ]
        then
            user_ok=1
            db_set coinpkg/conf_rpcuser $RET
            db_go || true
        else
            db_input high coinpkg/msg_wrong_user || true
            db_go || true
            db_set coinpkg/sysuser ""
        fi
    done
fi

db_input high coinpkg/conf_rpcuser || true
db_input high coinpkg/conf_rpcpwd || true
db_input high coinpkg/conf_rpcport || true
db_input high coinpkg/conf_extip || true
db_input high coinpkg/git_bootstrap || true
db_input high coinpkg/git_sentinel || true

db_go || true

db_get coinpkg/conf_extip


extip=$RET

if [ "$extip" = "0.0.0.0" ]
then
    get_ip=$(wget -qO- http://ipecho.net/plain ; echo)
    db_set coinpkg/conf_extip $get_ip
    db_input high coinpkg/conf_extip || true
    db_go || true
fi

db_get coinpkg/conf_rpcuser
rpcuser=$RET

db_get coinpkg/sysuser
sysuser=$RET

if [ ! $rpcuser ]
then
    db_set coinpkg/conf_rpcuser $sysuser
fi

db_get coinpkg/conf_rpcpwd
rpcpwd=$RET
if [[ ! $rpcpwd || "$rpcpwd" = *"true"* ]]
then
    rpcpwd=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
    db_set coinpkg/conf_rpcpwd $rpcpwd
fi

# Show interface
db_go || true
