#!/bin/bash

### Source debconf library. ###
. /usr/share/debconf/confmodule
set -e

### var settings for installation ###
# Coin configuration
coin_daemon="sparksd"

if [ -f "/etc/systemd/system/$coin_daemon.service" ]
then
  rm /etc/systemd/system/$coin_daemon.service
fi

systemctl daemon-reload
ldconfig
